"""TiRiFiC .def parameter metadata.

Source:
https://gigjozsa.github.io/tirific/parameter_index.html

Each key maps to:
- unit: physical or logical unit from the index table
- category: high-level category
- explanation: short behavior description
- Only per ring values should be labelled as "model" parameters, 
- "fitting" parameters should only relate to fitting modifycations
- "overhead" parameters that are not directly related to the model but are needed for I/O 
"""

DEFFILE_PARAMETERS = {
    "ACTION": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Specify reaction on present logfile."},
    "AZkP": {"unit": "degrees", "category": "Geometrical", "purpose": "model", "explanation": "Central positions of modelled azimuthal range (k = 1, 2)."},
    "AZkP_i": {"unit": "degrees", "category": "Geometrical", "purpose": "model", "explanation": "Central positions of modelled azimuthal range (k = 1, 2), ith disk."},
    "AZkW": {"unit": "degrees", "category": "Geometrical", "purpose": "model", "explanation": "Width of modelled azimuthal range (k = 1, 2)."},
    "AZkW_i": {"unit": "degrees", "category": "Geometrical", "purpose": "model", "explanation": "Width of modelled azimuthal range (k = 1, 2), ith disk."},
    "BIGTABLE": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Name of output table listing geometrical parameters per sub-ring."},
    "BIGTILT": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Name of output FITS file containing a tiltogram per sub-ring."},
    "BMAJ": {"unit": "arcsec", "category": "Geometrical", "purpose": "overhead", "explanation": "Observational beam HPBW, major axis."},
    "BMIN": {"unit": "arcsec", "category": "Geometrical", "purpose": "overhead", "explanation": "Observational beam HPBW, minor axis."},
    "BOX": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Obsolete parameter; keep empty."},
    "BPA": {"unit": "degrees", "category": "Geometrical", "purpose": "overhead", "explanation": "Position angle of observational beam major axis, measured anticlockwise from north."},
    "CALLITE": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "Maximum number of model calculations per iteration (FITMODE 2 only)."},
    "CFLUX": {"unit": "Jy km s-1", "category": "Geometrical", "purpose": "overhead", "explanation": "Point-source total flux of first disk."},
    "CFLUX_i": {"unit": "Jy km s-1", "category": "Geometrical", "purpose": "overhead", "explanation": "Point-source total flux of ith disk."},
    "CLNR": {"unit": "", "category": "Geometrical", "purpose": "overhead", "explanation": "Number of sub-clouds per cloud."},
    "CLNR_i": {"unit": "", "category": "Geometrical", "purpose": "overhead", "explanation": "Number of sub-clouds per cloud, ith disk."},
    "CONDISP": {"unit": "km s-1", "category": "Geometrical", "purpose": "overhead", "explanation": "Global velocity dispersion."},
    "COOLBEAM": {"unit": "arcsec", "category": "I/O", "purpose": "overhead", "explanation": "FWHM of convolving function for smoothing spatial 3D model in COOLGAL."},
    "COOLBIN": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Number of voxels along each axis per input voxel for COOLGAL."},
    "COOLGAL": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Name of output FITS file with spatial 3D realization of output model."},
    "DEFFILE": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Name of default file."},
    "DELEND": {"unit": "Defined with VARY", "category": "Fitting", "purpose": "fitting", "explanation": "Step width for MODERATE-th and later fitting loop."},
    "DELSTART": {"unit": "Defined with VARY", "category": "Fitting", "purpose": "fitting", "explanation": "Start step width for first fitting loop."},
    "DISTANCE": {"unit": "Mpc", "category": "I/O", "purpose": "overhead", "explanation": "Distance of object, used for output products."},
    "DVRA": {"unit": "km s-1 arcsec-1", "category": "Geometrical", "purpose": "model", "explanation": "Vertical gradient of radial velocity."},
    "DVRA_i": {"unit": "km s-1 arcsec-1", "category": "Geometrical", "purpose": "model", "explanation": "Vertical gradient of radial velocity, ith disk."},
    "DVRO": {"unit": "km s-1 arcsec-1", "category": "Geometrical", "purpose": "model", "explanation": "Vertical gradient of rotation velocity."},
    "DVRO_i": {"unit": "km s-1 arcsec-1", "category": "Geometrical", "purpose": "model", "explanation": "Vertical gradient of rotation velocity, ith disk."},
    "DVVE": {"unit": "km s-1 arcsec-1", "category": "Geometrical", "purpose": "model", "explanation": "Vertical gradient of vertical velocity."},
    "DVVE_i": {"unit": "km s-1 arcsec-1", "category": "Geometrical", "purpose": "model", "explanation": "Vertical gradient of vertical velocity, ith disk."},
    "FITMODE": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "Fitting mode selector (golden section/simplex variants)."},
    "GAkA": {"unit": "Jy km s-1 arcsec-2", "category": "Geometrical", "purpose": "model", "explanation": "Amplitude of kth Gaussian surface-brightness distortion (k = 1..4)."},
    "GAkA_i": {"unit": "Jy km s-1 arcsec-2", "category": "Geometrical", "purpose": "model", "explanation": "Amplitude of kth Gaussian surface-brightness distortion for ith disk."},
    "GAkD": {"unit": "arcsec", "category": "Geometrical", "purpose": "model", "explanation": "Dispersion of kth Gaussian surface-brightness distortion (k = 1..4)."},
    "GAkD_i": {"unit": "arcsec", "category": "Geometrical", "purpose": "model", "explanation": "Dispersion of kth Gaussian surface-brightness distortion for ith disk."},
    "GAkP": {"unit": "degrees", "category": "Geometrical", "purpose": "model", "explanation": "Phase of kth Gaussian surface-brightness distortion (k = 1..4)."},
    "GAkP_i": {"unit": "degrees", "category": "Geometrical", "purpose": "model", "explanation": "Phase of kth Gaussian surface-brightness distortion for ith disk."},
    "GR_COAD_i_j": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Pgplot color of jth additional data series, ith plot."},
    "GR_COL_i": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Pgplot color of main data series."},
    "GR_CONT": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Continue after plot flag."},
    "GR_DEVICE": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Pgplot device for parameter plot."},
    "GR_EBAD_i_j": {"unit": "ordinate units", "category": "I/O", "purpose": "overhead", "explanation": "Errors for data points, jth additional series, ith plot."},
    "GR_ERAD_i_j": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Plot error bars for jth additional series, ith plot."},
    "GR_ERRB_i": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Plot error bars for main data series."},
    "GR_ERRV_i": {"unit": "ordinate units", "category": "I/O", "purpose": "overhead", "explanation": "Error bars for main data series."},
    "GR_HLCA_i": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Pgplot colors of horizontal lines, ith plot."},
    "GR_HLVA_i": {"unit": "ordinate units", "category": "I/O", "purpose": "overhead", "explanation": "Positions of horizontal lines for ith plot."},
    "GR_HORL_i": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Number of horizontal lines for ith plot."},
    "GR_INTERPAD_i_j=": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Interpolation scheme for lines in jth additional series, ith plot."},
    "GR_INTER_i=": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Interpolation scheme for lines in main data series."},
    "GR_LGND": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Plot legend with axis descriptors."},
    "GR_LIAD_i_j": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Draw lines between points for jth additional series, ith plot."},
    "GR_LINES_i": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Draw lines for main data series."},
    "GR_ML": {"unit": "TXHT=", "category": "I/O", "purpose": "overhead", "explanation": "Margin between plot and left axis descriptors."},
    "GR_MR": {"unit": "TXHT=", "category": "I/O", "purpose": "overhead", "explanation": "Margin between plot and right axis descriptors."},
    "GR_NPAD_i_j": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Number of data points in jth additional series of ith plot."},
    "GR_NRAD_i": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Number of additional series for ith plot."},
    "GR_PARMS": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Parameters to plot, first parameter on abscissa."},
    "GR_PRFR": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Reference ring for central position."},
    "GR_PRFX": {"unit": "deg", "category": "I/O", "purpose": "overhead", "explanation": "Right ascension of reference position."},
    "GR_PRFY": {"unit": "deg", "category": "I/O", "purpose": "overhead", "explanation": "Declination of reference position."},
    "GR_SBHT": {"unit": "TXHT=", "category": "I/O", "purpose": "overhead", "explanation": "Symbol height."},
    "GR_SBRP": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Plot sub-rings flag."},
    "GR_SIAD_i_j": {"unit": "TXHT=", "category": "I/O", "purpose": "overhead", "explanation": "Size of pgplot symbols in jth additional series, ith plot."},
    "GR_SIZE_i": {"unit": "TXHT=", "category": "I/O", "purpose": "overhead", "explanation": "Symbol size for main data series."},
    "GR_SYAD_i_j": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Pgplot symbol of data points, jth additional series, ith plot."},
    "GR_SYMB_i": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Pgplot symbol for main data series, ith plot."},
    "GR_TXHT": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Text height in pgplot units."},
    "GR_VERL_i": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Number of vertical lines in ith plot."},
    "GR_VLCA_i": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Pgplot colors of vertical lines, ith plot."},
    "GR_VLVA_i": {"unit": "abscissa units", "category": "I/O", "purpose": "overhead", "explanation": "Positions of vertical lines for ith plot."},
    "GR_XLOG": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Format abscissa logarithmically."},
    "GR_XMAX": {"unit": "abscissa units", "category": "I/O", "purpose": "overhead", "explanation": "Maximum abscissa axis range."},
    "GR_XMIN": {"unit": "abscissa units", "category": "I/O", "purpose": "overhead", "explanation": "Minimum abscissa axis range."},
    "GR_XPAD_i_j": {"unit": "abscissa units", "category": "I/O", "purpose": "overhead", "explanation": "Abscissa values of jth additional series, ith plot."},
    "GR_YLOG_i": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Format ordinate axis logarithmically for ith plot."},
    "GR_YMAX_i": {"unit": "ordinate units", "category": "I/O", "purpose": "overhead", "explanation": "Maximum ordinate axis range, ith plot."},
    "GR_YMIN_i": {"unit": "ordinate units", "category": "I/O", "purpose": "overhead", "explanation": "Minimum ordinate axis range, ith plot."},
    "GR_YPAD_i_j": {"unit": "ordinate units", "category": "I/O", "purpose": "overhead", "explanation": "Ordinate values of jth additional series, ith plot."},
    "INCL": {"unit": "degrees", "category": "Geometrical", "purpose": "model", "explanation": "Inclination."},
    "INCL_i": {"unit": "degrees", "category": "Geometrical", "purpose": "model", "explanation": "Inclination, ith disk."},
    "INCLINO": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Output inclinogram FITS cube (first disk only)."},
    "INDINTY": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "Interpolation scheme between parameters indexed by VARINDX."},
    "INIMODE": {"unit": "", "category": "Generic", "purpose": "overhead","explanation": "FFT initialization mode (0-3)."},
    "INSET": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Name of input data set."},
    "INTY": {"unit": "", "category": "Geometrical", "purpose": "fitting", "explanation": "Interpolation scheme for sub-grid (sub-ring) parameters."},
    "IN_REFINE": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Increase of TILT spatial resolution compared to input data cube."},
    "ISEED": {"unit": "", "category": "Geometrical", "purpose": "fitting", "explanation": "Random-number generator seed."},
    "ITEEND": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "Maximum model generations for MODERATE-th and later fitting loop."},
    "ITESTART": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "Maximum model generations for first fitting loop."},
    "ITOU": {"unit": "atoms cm-2 (Jy km s-1 arcsec-2)-1", "category": "I/O", "purpose": "overhead", "explanation": "Conversion from Jy km s-1 arcsec-2 to HI atoms cm-2."},
    "LC0": {"unit": "arcsec", "category": "Geometrical", "purpose": "model", "explanation": "Shift along projected major axis."},
    "LC0_i": {"unit": "arcsec", "category": "Geometrical", "purpose": "model", "explanation": "Shift along projected major axis, ith disk."},
    "LOGNAME": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Name of logfile."},
    "LOOPS": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "Maximum number of repeated major fitting loops."},
    "LS0": {"unit": "arcsec", "category": "Geometrical", "purpose": "model", "explanation": "Shift along projected minor axis."},
    "LS0_i": {"unit": "arcsec", "category": "Geometrical", "purpose": "model", "explanation": "Shift along projected minor axis, ith disk."},
    "LTYPE": {"unit": "", "category": "Geometrical", "purpose": "overhead", "explanation": "Vertical density distribution type."},
    "LTYPE_i": {"unit": "", "category": "Geometrical", "purpose": "overhead", "explanation": "Vertical density distribution type, ith disk."},
    "MAXITER": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "Maximum number of iterations for complete fitting process."},
    "MINDELTA": {"unit": "Defined with VARY=", "category": "Fitting", "purpose": "fitting", "explanation": "Fitting grid normalization (minimal step width)."},
    "MODERATE": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "Loops to interpolate between fit parameters."},
    "NCORES": {"unit": "", "category": "Generic", "purpose": "overhead", "explanation": "Number of computing cores."},
    "NDISKS": {"unit": "", "category": "Geometrical", "purpose": "model", "explanation": "Number of disks."},
    "NUR": {"unit": "", "category": "Geometrical", "purpose": "model", "explanation": "Number of grid nodes (ring radii)."},
    "OUTCUBUP": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Frequency of updating OUTSET."},
    "OUTSET": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Name of output data cube."},
    "PA": {"unit": "degrees", "category": "Geometrical", "purpose": "model", "explanation": "Position angle."},
    "PA_i": {"unit": "degrees", "category": "Geometrical", "purpose": "model", "explanation": "Position angle, ith disk."},
    "PARMAX": {"unit": "Defined with VARY=", "category": "Fitting", "purpose": "fitting", "explanation": "Fitting constraint maxima."},
    "PARMIN": {"unit": "Defined with VARY=", "category": "Fitting", "purpose": "fitting", "explanation": "Fitting constraint minima."},
    "PENALTY": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "Outlier penalization strength in cube fitting."},
    "PROMPT": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Prompt on error flag."},
    "PSW_PSCO": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "PSWARM cognition parameter."},
    "PSW_PSDD": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "PSWARM decrease delta."},
    "PSW_PSFI": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "PSWARM final weight."},
    "PSW_PSID": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "PSWARM increase delta."},
    "PSW_PSII": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "PSWARM initial weight."},
    "PSW_PSMV": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "PSWARM maximum velocity."},
    "PSW_PSNF": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "PSWARM function evaluations from initial to final weight."},
    "PSW_PSNP": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "PSWARM number of particles."},
    "PSW_PSSE": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "PSWARM seed."},
    "RADI": {"unit": "arcsec", "category": "Geometrical", "purpose": "model", "explanation": "List of grid nodes (ring radii)."},
    "RADSEP": {"unit": "pixel", "category": "Geometrical", "purpose": "overhead", "explanation": "Separation of sub-grids (sub-rings)."},
    "RADSEP_i": {"unit": "pixel", "category": "Geometrical", "purpose": "overhead", "explanation": "Separation of sub-grids (sub-rings), ith disk."},
    "RAkA": {"unit": "km s-1", "category": "Geometrical", "purpose": "model", "explanation": "Amplitude of kth harmonic radial velocity term."},
    "RAkA_i": {"unit": "km s-1", "category": "Geometrical", "purpose": "model", "explanation": "Amplitude of kth harmonic radial velocity term, ith disk."},
    "RAkP": {"unit": "degrees", "category": "Geometrical", "purpose": "model", "explanation": "Phase of kth harmonic radial velocity term."},
    "RAkP_i": {"unit": "degrees", "category": "Geometrical", "purpose": "model", "explanation": "Phase of kth harmonic radial velocity term, ith disk."},
    "REFRING": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Reference node for intrinsic parameter calculations."},
    "REGAMPD": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "Absolute denominator value in harmonic regularization."},
    "REGAMPL": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "Constant penalty in harmonic regularization."},
    "REGASTE": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "Loop-dependent proportionality in harmonic regularization."},
    "REGDENO": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "Comma-separated denominator orders for regularization."},
    "REGNUME": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "Comma-separated numerator orders for regularization."},
    "REGPARA": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "Comma-separated parameters used in regularization."},
    "RESTARTID": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "ID for restarting TiRiFiC."},
    "RESTARTNAME": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "File name for restarting TiRiFiC."},
    "REGTHRE": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "Threshold value for harmonic ratio penalty."},
    "REGWIDT": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "Width for harmonic ratio until maximum penalty is reached."},
    "RMS": {"unit": "map units (Jy km s-1)", "category": "Fitting", "purpose": "fitting", "explanation": "RMS noise in input data cube."},
    "ROkA": {"unit": "km s-1", "category": "Geometrical", "purpose": "model", "explanation": "Amplitude of kth harmonic tangential (rotation) velocity term."},
    "ROkA_i": {"unit": "km s-1", "category": "Geometrical", "purpose": "model", "explanation": "Amplitude of kth harmonic tangential velocity term, ith disk."},
    "ROkP": {"unit": "degrees", "category": "Geometrical", "purpose": "model", "explanation": "Phase of kth harmonic tangential velocity term."},
    "ROkP_i": {"unit": "degrees", "category": "Geometrical", "purpose": "model", "explanation": "Phase of kth harmonic tangential velocity term, ith disk."},
    "SATDELT": {"unit": "Defined with VARY=", "category": "Fitting", "purpose": "fitting", "explanation": "Stopping condition after a loop (FITMODE 1)."},
    "SBR": {"unit": "Jy km s-1 arcsec-2", "category": "Geometrical", "purpose": "model", "explanation": "Constant surface brightness (first disk)."},
    "SBR_i": {"unit": "Jy km s-1 arcsec-2", "category": "Geometrical", "purpose": "model", "explanation": "Constant surface brightness, ith disk."},
    "SDIS": {"unit": "km s-1", "category": "Geometrical", "purpose": "model", "explanation": "Radially dependent velocity dispersion."},
    "SDIS_i": {"unit": "km s-1", "category": "Geometrical", "purpose": "model", "explanation": "Radially dependent velocity dispersion, ith disk."},
    "SIZE": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "Stopping size of minimization process (in units of MINDELTA)."},
    "SMkA": {"unit": "Jy km s-1 arcsec-2", "category": "Geometrical", "purpose": "model", "explanation": "Amplitude of kth harmonic surface-brightness distortion."},
    "SMkA_i": {"unit": "Jy km s-1 arcsec-2", "category": "Geometrical", "purpose": "model", "explanation": "Amplitude of kth harmonic surface-brightness distortion, ith disk."},
    "SMkP": {"unit": "degrees", "category": "Geometrical", "purpose": "model", "explanation": "Phase of kth harmonic surface-brightness distortion."},
    "SMkP_i": {"unit": "degrees", "category": "Geometrical", "purpose": "model", "explanation": "Phase of kth harmonic surface-brightness distortion, ith disk."},
    "TABLE": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Name of output table listing geometrical parameters per node."},
    "TILT": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Name of output FITS file containing a tiltogram per ring."},
    "TIRACC": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Numerical accuracy for output .def files TIRDEF and TIRSMO."},
    "TIRDEF": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Name of output TiRiFiC .def file for repeated fitting runs."},
    "TIRLEN": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Length of Hanning filter used for TIRSMO."},
    "TIRNR": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Number of rings in output .def files TIRDEF and TIRSMO."},
    "TIRRAD": {"unit": "arcsec", "category": "I/O", "purpose": "overhead", "explanation": "Radii of nodes in output .def files TIRDEF and TIRSMO."},
    "TIRSMO": {"unit": "", "category": "I/O", "purpose": "overhead", "explanation": "Hanning-filtered version of TIRDEF."},
    "VARINDX": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "List of radial nodes ignored for a given parameter."},
    "VARY": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "Specification of fitting parameters."},
    "VM0A": {"unit": "km s-1", "category": "Geometrical", "purpose": "model", "explanation": "0th-order LOS harmonic amplitude (constant velocity shift)."},
    "VM0A_i": {"unit": "km s-1", "category": "Geometrical", "purpose": "model", "explanation": "0th-order LOS harmonic amplitude for ith disk."},
    "VMkA": {"unit": "km s-1", "category": "Geometrical", "purpose": "model", "explanation": "Amplitude of kth LOS velocity harmonic term."},
    "VMkA_i": {"unit": "km s-1", "category": "Geometrical", "purpose": "model", "explanation": "Amplitude of kth LOS velocity harmonic term, ith disk."},
    "VMkP": {"unit": "degrees", "category": "Geometrical", "purpose": "model", "explanation": "Phase of kth LOS velocity harmonic term."},
    "VMkP_i": {"unit": "degrees", "category": "Geometrical", "purpose": "model", "explanation": "Phase of kth LOS velocity harmonic term, ith disk."},
    "VRAD": {"unit": "km s-1", "category": "Geometrical", "purpose": "model", "explanation": "Mid-plane radial velocity (outward positive)."},
    "VRAD_i": {"unit": "km s-1", "category": "Geometrical", "purpose": "model", "explanation": "Mid-plane radial velocity, ith disk."},
    "VROT": {"unit": "km s-1", "category": "Geometrical", "purpose": "model", "explanation": "Mid-plane rotation velocity."},
    "VROT_i": {"unit": "km s-1", "category": "Geometrical", "purpose": "model", "explanation": "Mid-plane rotation velocity, ith disk."},
    "VSYS": {"unit": "km s-1", "category": "Geometrical", "purpose": "model", "explanation": "Systemic (recession) velocity."},
    "VSYS_i": {"unit": "km s-1", "category": "Geometrical", "purpose": "model", "explanation": "Systemic (recession) velocity, ith disk."},
    "VVER": {"unit": "km s-1", "category": "Geometrical", "purpose": "model", "explanation": "Mid-plane vertical velocity."},
    "VVER_i": {"unit": "km s-1", "category": "Geometrical", "purpose": "model", "explanation": "Mid-plane vertical velocity, ith disk."},
    "WEIGHT": {"unit": "", "category": "Fitting", "purpose": "fitting", "explanation": "Continuous parameter accounting for quantization noise in chi2."},
    "WM0A": {"unit": "arcsec", "category": "Geometrical", "purpose": "model", "explanation": "0th-order harmonic vertical displacement amplitude."},
    "WM0A_i": {"unit": "arcsec", "category": "Geometrical", "purpose": "model", "explanation": "0th-order harmonic vertical displacement amplitude, ith disk."},
    "WMkA": {"unit": "arcsec", "category": "Geometrical", "purpose": "model", "explanation": "Amplitude of kth harmonic vertical displacement."},
    "WMkA_i": {"unit": "arcsec", "category": "Geometrical", "purpose": "model", "explanation": "Amplitude of kth harmonic vertical displacement, ith disk."},
    "WMkP": {"unit": "degrees", "category": "Geometrical", "purpose": "model", "explanation": "Phase of kth harmonic vertical displacement."},
    "WMkP_i": {"unit": "degrees", "category": "Geometrical", "purpose": "model", "explanation": "Phase of kth harmonic vertical displacement, ith disk."},
    "XPOS": {"unit": "degrees", "category": "Geometrical", "purpose": "model", "explanation": "Right ascension."},
    "XPOS_i": {"unit": "degrees", "category": "Geometrical", "purpose": "model", "explanation": "Right ascension, ith disk."},
    "YPOS": {"unit": "degrees", "category": "Geometrical", "purpose": "model", "explanation": "Declination."},
    "YPOS_i": {"unit": "degrees", "category": "Geometrical", "purpose": "model", "explanation": "Declination, ith disk."},
    "Z0": {"unit": "arcsec", "category": "Geometrical", "purpose": "model", "explanation": "Disk thickness."},
    "Z0_i": {"unit": "arcsec", "category": "Geometrical", "purpose": "model", "explanation": "Disk thickness, ith disk."},
    "ZDRA": {"unit": "arcsec", "category": "Geometrical", "purpose": "model", "explanation": "Vertical gradient scale of radial velocity."},
    "ZDRA_i": {"unit": "arcsec", "category": "Geometrical", "purpose": "model", "explanation": "Vertical gradient scale of radial velocity, ith disk."},
    "ZDRO": {"unit": "arcsec", "category": "Geometrical", "purpose": "model", "explanation": "Vertical gradient scale of rotation velocity."},
    "ZDRO_i": {"unit": "arcsec", "category": "Geometrical", "purpose": "model", "explanation": "Vertical gradient scale of rotation velocity, ith disk."},
    "ZDVE": {"unit": "arcsec", "category": "Geometrical", "purpose": "model", "explanation": "Vertical gradient scale of vertical velocity."},
    "ZDVE_i": {"unit": "arcsec", "category": "Geometrical", "purpose": "model", "explanation": "Vertical gradient scale of vertical velocity, ith disk."},
}
